workspace:
  launch:
    button:
      name: ğŸ›« èµ·é£
      description: ğŸ’ª é€æ­¥è¿ˆå‘è¿ç»´çš„å››ä¸ªç°ä»£åŒ–ï¼šè§„èŒƒåŒ–ï¼Œæ ‡å‡†åŒ–ï¼Œé«˜æ•ˆåŒ–ï¼Œä¼˜é›…åŒ–
    cpus: 8
    disabled: false
    autoOpenWebIDE: false