name: Build Deploy

# 在main分支发生push事件时触发。
on:
  push:
    branches:
      - main

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      # - name: run deploy.sh # 步骤3
      #   env: # 设置环境变量
      #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
      #   run: npm install && npm run deploy

      - name: Build and Deploy # 步骤3 （只提交到github可以使用这个步骤）
        uses: JamesIves/github-pages-deploy-action@4.1.4
        env: # 设置环境变量
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
        with:
          branch: gh-pages # 部署到的分支
          folder: docs/.vuepress/dist # 要部署的文件夹.
          BUILD_SCRIPT: npm install && npm run build && cd docs/.vuepress/dist


      # 利用action把build好的文件上传到服务器/home/eryajf.github.io路径下,需要确认此目录已在服务端创建
      # - name: deploy file to server
      #   uses: wlixcc/SFTP-Deploy-Action@v1.0
      #   with:
      #     username: 'root'   #ssh user name
      #     port: '22' # 远程服务器ssh端口，默认22
      #     server: '8.136.215.57' # 远程服务器IP
      #     ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # 认证服务器秘钥对的私钥
      #     local_path: 'docs/.vuepress/dist/*'  # 对应我们项目打包后的静态文件路径
      #     remote_path: '/data/www/HowToStartOpenSource.eryajf.net' # 服务器上的路径